package com.ivieleague.smbtranslation

import com.ivieleague.smbtranslation.utils.JoypadBits
import com.ivieleague.smbtranslation.utils.PpuControl
import com.ivieleague.smbtranslation.utils.PpuMask
import com.ivieleague.smbtranslation.utils.SpriteFlags

annotation class RamLocation(val address: Int)

class GameRam {
    val stack = Stack()

    inner class Stack {
        val data = ByteArray(0xFF)
        var currentIndex: Int = 0
        fun push(byte: Byte) {
            data[currentIndex++] = byte
        }

        fun pop(): Byte = data[--currentIndex]
        fun clear() {
            currentIndex = 0
        }
    }

    @RamLocation(0x8) var objectOffset: Byte = 0
    @RamLocation(0x9) var frameCounter: Byte = 0
    var savedJoypadBits: JoypadBits = JoypadBits(0)
    var savedJoypad1Bits: JoypadBits = JoypadBits(0)
    var savedJoypad2Bits: JoypadBits = JoypadBits(0)
    @RamLocation(0x74a) var joypadBitMask: Byte = 0
    @RamLocation(0x758) var joypadOverride: Byte = 0
    @RamLocation(0xa) var aBButtons: Byte = 0
    @RamLocation(0xd) var previousABButtons: Byte = 0
    @RamLocation(0xb) var upDownButtons: Byte = 0
    @RamLocation(0xc) var leftRightButtons: Byte = 0
    @RamLocation(0xe) var gameEngineSubroutine: Byte = 0
    var mirrorPPUCTRLREG1: PpuControl = PpuControl(0)
    var mirrorPPUCTRLREG2: PpuMask = PpuMask(0)
    @RamLocation(0x770) var operMode: OperMode = OperMode.TitleScreen
    @RamLocation(0x772) var operModeTask: Byte = 0
    @RamLocation(0x73c) var screenRoutineTask: Byte = 0
    @RamLocation(0x776) var gamePauseStatus: Byte = 0
    @RamLocation(0x777) var gamePauseTimer: Byte = 0
    @RamLocation(0x717) var demoAction: Byte = 0
    @RamLocation(0x718) var demoActionTimer: Byte = 0
    @RamLocation(0x747) var timerControl: Byte = 0
    @RamLocation(0x77f) var intervalTimerControl: Byte = 0
    @RamLocation(0x780) val timers = ByteArray(0x23)
    @RamLocation(0x780) var selectTimer: Byte = 0
    @RamLocation(0x781) var playerAnimTimer: Byte = 0
    @RamLocation(0x782) var jumpSwimTimer: Byte = 0
    @RamLocation(0x783) var runningTimer: Byte = 0
    @RamLocation(0x784) var blockBounceTimer: Byte = 0
    @RamLocation(0x785) var sideCollisionTimer: Byte = 0
    @RamLocation(0x786) var jumpspringTimer: Byte = 0
    @RamLocation(0x787) var gameTimerCtrlTimer: Byte = 0
    @RamLocation(0x789) var climbSideTimer: Byte = 0
    @RamLocation(0x78a) var enemyFrameTimer: Byte = 0
    @RamLocation(0x78f) var frenzyEnemyTimer: Byte = 0
    @RamLocation(0x790) var bowserFireBreathTimer: Byte = 0
    @RamLocation(0x791) var stompTimer: Byte = 0
    @RamLocation(0x792) var airBubbleTimer: Byte = 0
    @RamLocation(0x795) var scrollIntervalTimer: Byte = 0
    @RamLocation(0x796) var enemyIntervalTimer: Byte = 0
    @RamLocation(0x79d) var brickCoinTimer: Byte = 0
    @RamLocation(0x79e) var injuryTimer: Byte = 0
    @RamLocation(0x79f) var starInvincibleTimer: Byte = 0
    @RamLocation(0x7a0) var screenTimer: Byte = 0
    @RamLocation(0x7a1) var worldEndTimer: Byte = 0
    @RamLocation(0x7a2) var demoTimer: Byte = 0

    class Sprite(val offset: Int) {
        var y: UByte = 0u  // offset
        var tilenumber: Byte = 0  // offset + 1
        var attributes: SpriteFlags = SpriteFlags(0)  // offset + 2
        var x: UByte = 0u  // offset + 3
    }
    @RamLocation(0x200) val sprites = Array(64) { Sprite(it * 4 + 0x200) }

    @RamLocation(0x71a) var screenEdgePageLoc: Byte = 0
    @RamLocation(0x71c) var screenEdgeXPos: Byte = 0
    @RamLocation(0x71a) var screenLeftPageLoc: Byte = 0
    @RamLocation(0x71b) var screenRightPageLoc: Byte = 0
    @RamLocation(0x71c) var screenLeftXPos: Byte = 0
    @RamLocation(0x71d) var screenRightXPos: Byte = 0
    @RamLocation(0x33) var playerFacingDir: Byte = 0
    @RamLocation(0x34) var destinationPageLoc: Byte = 0
    @RamLocation(0x35) var victoryWalkControl: Byte = 0
    @RamLocation(0x768) var scrollFractional: Byte = 0
    @RamLocation(0x719) var primaryMsgCounter: Byte = 0
    @RamLocation(0x749) var secondaryMsgCounter: Byte = 0
    @RamLocation(0x73f) var horizontalScroll: Byte = 0
    @RamLocation(0x740) var verticalScroll: Byte = 0
    @RamLocation(0x723) var scrollLock: Byte = 0
    @RamLocation(0x73d) var scrollThirtyTwo: Byte = 0
    @RamLocation(0x6ff) var playerXScroll: Byte = 0
    @RamLocation(0x755) var playerPosForScroll: Byte = 0
    @RamLocation(0x775) var scrollAmount: Byte = 0
    @RamLocation(0xe7) var areaData: Byte = 0
    @RamLocation(0xe7) var areaDataLow: Byte = 0
    @RamLocation(0xe8) var areaDataHigh: Byte = 0
    @RamLocation(0xe9) var enemyData: Byte = 0
    @RamLocation(0xe9) var enemyDataLow: Byte = 0
    @RamLocation(0xea) var enemyDataHigh: Byte = 0
    @RamLocation(0x71f) var areaParserTaskNum: Byte = 0
    @RamLocation(0x71e) var columnSets: Byte = 0
    @RamLocation(0x725) var currentPageLoc: Byte = 0
    @RamLocation(0x726) var currentColumnPos: Byte = 0
    @RamLocation(0x728) var backloadingFlag: Byte = 0
    @RamLocation(0x729) var behindAreaParserFlag: Byte = 0
    @RamLocation(0x72a) var areaObjectPageLoc: Byte = 0
    @RamLocation(0x72b) var areaObjectPageSel: Byte = 0
    @RamLocation(0x72c) var areaDataOffset: Byte = 0
    @RamLocation(0x72d) var areaObjOffsetBuffer: Byte = 0
    @RamLocation(0x730) var areaObjectLength: Byte = 0
    @RamLocation(0x734) var staircaseControl: Byte = 0
    @RamLocation(0x735) var areaObjectHeight: Byte = 0
    @RamLocation(0x736) var mushroomLedgeHalfLen: Byte = 0
    @RamLocation(0x739) var enemyDataOffset: Byte = 0
    @RamLocation(0x73a) var enemyObjectPageLoc: Byte = 0
    @RamLocation(0x73b) var enemyObjectPageSel: Byte = 0
    @RamLocation(0x6a1) val metatileBuffer: ByteArray = ByteArray(0x0d)
    @RamLocation(0x6a0) var blockBufferColumnPos: Byte = 0
    @RamLocation(0x721) var currentNTAddrLow: Byte = 0
    @RamLocation(0x720) var currentNTAddrHigh: Byte = 0
    // Attribute buffer used during rendering; modeled as a small array of rows.
    @RamLocation(0x3f9) val attributeBuffer: ByteArray = ByteArray(0x20)
    @RamLocation(0x745) var loopCommand: Byte = 0
    @RamLocation(0x7d7) var displayDigits: Byte = 0

    @RamLocation(0x7d7) val topScoreDisplay = ByteArray(6)

    @RamLocation(0x7dd) val scoreAndCoinDisplay = ByteArray(0x18)
    @RamLocation(0x7dd) var playerScoreDisplay: Byte = 0
    @RamLocation(0x7f8) var gameTimerDisplay: Byte = 0
    @RamLocation(0x134) val digitModifier: ByteArray = ByteArray(999)
    // Placeholder bookkeeping for score updates triggered by floatey numbers
    var lastScoreDigitIndex: Byte = 0
    var lastScoreDigitAdd: Byte = 0
    @RamLocation(0x109) var verticalFlipFlag: Byte = 0
    @RamLocation(0x110) val floateyNumControl: ByteArray = ByteArray(ComboInfo.list.size)
    @RamLocation(0x117) var floateyNumXPos: UByteArray = UByteArray(ComboInfo.list.size)
    @RamLocation(0x11e) var floateyNumYPos: UByteArray = UByteArray(ComboInfo.list.size)
    @RamLocation(0x12c) val floateyNumTimer: ByteArray = ByteArray(ComboInfo.list.size)
    @RamLocation(0x125) var shellChainCounter: Byte = 0

    @RamLocation(0x10d) var flagpoleFNumYPos: Byte = 0
    @RamLocation(0x10e) var flagpoleFNumYMFDummy: Byte = 0
    @RamLocation(0x10f) var flagpoleScore: Byte = 0
    @RamLocation(0x70f) var flagpoleCollisionYPos: Byte = 0
    @RamLocation(0x484) var stompChainCounter: Byte = 0

    @RamLocation(0x300) val vRAMBuffer1 = MutableVBuffer()
    @RamLocation(0x340) val vRAMBuffer2 = MutableVBuffer()

    @RamLocation(0x773) var vRAMBufferAddrCtrl: Byte = 0

    @RamLocation(0x722) var sprite0HitDetectFlag: Boolean = false
    @RamLocation(0x774) var disableScreenFlag: Boolean = false
    @RamLocation(0x769) var disableIntermediate: Boolean = false
    @RamLocation(0x6d4) var colorRotateOffset: Byte = 0
    @RamLocation(0x727) var terrainControl: Byte = 0
    @RamLocation(0x733) var areaStyle: Byte = 0
    @RamLocation(0x741) var foregroundScenery: Byte = 0
    @RamLocation(0x742) var backgroundScenery: Byte = 0
    @RamLocation(0x743) var cloudTypeOverride: Byte = 0
    @RamLocation(0x744) var backgroundColorCtrl: Byte = 0
    @RamLocation(0x74e) var areaType: Byte = 0
    @RamLocation(0x74f) var areaAddrsLOffset: Byte = 0
    @RamLocation(0x750) var areaPointer: Byte = 0
    @RamLocation(0x710) var playerEntranceCtrl: Byte = 0
    @RamLocation(0x715) var gameTimerSetting: Byte = 0
    @RamLocation(0x752) var altEntranceControl: Byte = 0
    @RamLocation(0x751) var entrancePage: Byte = 0
    @RamLocation(0x77a) var numberOfPlayers: Byte = 0
    @RamLocation(0x6d6) var warpZoneControl: Byte = 0
    @RamLocation(0x6de) var changeAreaTimer: Byte = 0
    @RamLocation(0x6d9) var multiLoopCorrectCntr: Byte = 0
    @RamLocation(0x6da) var multiLoopPassCntr: Byte = 0
    @RamLocation(0x757) var fetchNewGameTimerFlag: Boolean = false
    @RamLocation(0x759) var gameTimerExpiredFlag: Boolean = false
    @RamLocation(0x76a) var primaryHardMode: Boolean = false
    @RamLocation(0x6cc) var secondaryHardMode: Byte = 0
    @RamLocation(0x76b) var worldSelectNumber: Byte = 0
    @RamLocation(0x7fc) var worldSelectEnableFlag: Boolean = false
    @RamLocation(0x7fd) var continueWorld: Byte = 0
    @RamLocation(0x753) var currentPlayer: Byte = 0
    @RamLocation(0x754) var playerSize: Byte = 0
    @RamLocation(0x756) var playerStatus: Byte = 0
    @RamLocation(0x75a) var onscreenPlayerInfo: Byte = 0
    @RamLocation(0x75a) var numberofLives: Byte = 0
    @RamLocation(0x75b) var halfwayPage: Byte = 0
    @RamLocation(0x75c) var levelNumber: Byte = 0
    @RamLocation(0x75d) var hidden1UpFlag: Boolean = false
    @RamLocation(0x75e) var coinTally: Byte = 0
    @RamLocation(0x75f) var worldNumber: Byte = 0
    @RamLocation(0x760) var areaNumber: Byte = 0
    @RamLocation(0x748) var coinTallyFor1Ups: Byte = 0
    @RamLocation(0x761) var offscreenPlayerInfo: Byte = 0
    @RamLocation(0x761) var offScrNumberofLives: Byte = 0
    @RamLocation(0x762) var offScrHalfwayPage: Byte = 0
    @RamLocation(0x763) var offScrLevelNumber: Byte = 0
    @RamLocation(0x764) var offScrHidden1UpFlag: Boolean = false
    @RamLocation(0x765) var offScrCoinTally: Byte = 0
    @RamLocation(0x766) var offScrWorldNumber: Byte = 0
    @RamLocation(0x767) var offScrAreaNumber: Byte = 0
    @RamLocation(0x3a0) var balPlatformAlignment: Byte = 0
    @RamLocation(0x3a1) var platformXScroll: Byte = 0
    @RamLocation(0x3a2) var platformCollisionFlag: Byte = 0
    @RamLocation(0x401) var yPlatformTopYPos: Byte = 0
    @RamLocation(0x58) var yPlatformCenterYPos: Byte = 0
    @RamLocation(0x6bc) var brickCoinTimerFlag: Byte = 0
    @RamLocation(0x746) var starFlagTaskControl: Byte = 0
    @RamLocation(0x7a7) val pseudoRandomBitReg = ByteArray(8)
    @RamLocation(0x7ff) var warmBootValidation: Boolean = false // by BooleanAccess(, trueValue = 0xa5.toByte())
    @RamLocation(0x6e0) var sprShuffleAmtOffset: Byte = 0
    @RamLocation(0x6e1) val sprShuffleAmt = ByteArray(9999)

    // SprDataOffset is a contiguous table of 15 bytes starting at $6E4 used by SpriteShuffler
    @RamLocation(0x6e4) val sprDataOffsets = ByteArray(0x0f)

    @RamLocation(0x6e4) var playerSprDataOffset: Byte = 0
    @RamLocation(0x6e5) val enemySprDataOffset: ByteArray = ByteArray(999)
    @RamLocation(0x6ec) var blockSprDataOffset: Byte = 0
    @RamLocation(0x6ec) val altSprDataOffset: ByteArray = ByteArray(999)
    @RamLocation(0x6ee) var bubbleSprDataOffset: Byte = 0
    @RamLocation(0x6f1) var fBallSprDataOffset: Byte = 0

    // Misc_SprDataOffset is a contiguous table of 9 bytes starting at $6F3
    @RamLocation(0x6f3) val miscSprDataOffsets = ByteArray(9)
    @RamLocation(0x6f3) var miscSprDataOffset: Byte = 0

    @RamLocation(0x3ee) var sprDataOffsetCtrl: Byte = 0
    @RamLocation(0x1d) var playerState: Byte = 0
    @RamLocation(0x1e) val enemyState = ByteArray(999)
    @RamLocation(0x24) var fireballState: Byte = 0
    @RamLocation(0x26) var blockState: Byte = 0
    @RamLocation(0x2a) var miscState: Byte = 0
    @RamLocation(0x45) var playerMovingDir: Byte = 0
    @RamLocation(0x46) var enemyMovingDir: Byte = 0
    @RamLocation(0x57) var sprObjectXSpeed: Byte = 0
    @RamLocation(0x57) var playerXSpeed: Byte = 0
    @RamLocation(0x58) var enemyXSpeed: Byte = 0
    @RamLocation(0x5e) var fireballXSpeed: Byte = 0
    @RamLocation(0x60) var blockXSpeed: Byte = 0
    @RamLocation(0x64) var miscXSpeed: Byte = 0
    @RamLocation(0x58) var jumpspringFixedYPos: Byte = 0
    @RamLocation(0x70e) var jumpspringAnimCtrl: Byte = 0
    @RamLocation(0x6db) var jumpspringForce: Byte = 0
    @RamLocation(0x6d) var sprObjectPageLoc: Byte = 0
    @RamLocation(0x6d) var playerPageLoc: Byte = 0
    @RamLocation(0x6e) var enemyPageLoc: Byte = 0
    @RamLocation(0x74) var fireballPageLoc: Byte = 0
    @RamLocation(0x76) var blockPageLoc: Byte = 0
    @RamLocation(0x7a) var miscPageLoc: Byte = 0
    @RamLocation(0x83) var bubblePageLoc: Byte = 0
    @RamLocation(0x86) var sprObjectXPosition: Byte = 0
    @RamLocation(0x86) var playerXPosition: UByte = 0u
    @RamLocation(0x87) var enemyXPosition: Byte = 0
    @RamLocation(0x8d) var fireballXPosition: Byte = 0
    @RamLocation(0x8f) var blockXPosition: Byte = 0
    @RamLocation(0x93) var miscXPosition: Byte = 0
    @RamLocation(0x9c) var bubbleXPosition: Byte = 0
    @RamLocation(0x9f) var sprObjectYSpeed: Byte = 0
    @RamLocation(0x9f) var playerYSpeed: Byte = 0
    @RamLocation(0xa0) var enemyYSpeed: Byte = 0
    @RamLocation(0xa6) var fireballYSpeed: Byte = 0
    @RamLocation(0xa8) var blockYSpeed: Byte = 0
    @RamLocation(0xac) var miscYSpeed: Byte = 0
    @RamLocation(0xb5) var sprObjectYHighPos: Byte = 0
    @RamLocation(0xb5) var playerYHighPos: Byte = 0
    @RamLocation(0xb6) var enemyYHighPos: Byte = 0
    @RamLocation(0xbc) var fireballYHighPos: Byte = 0
    @RamLocation(0xbe) var blockYHighPos: Byte = 0
    @RamLocation(0xc2) var miscYHighPos: Byte = 0
    @RamLocation(0xcb) var bubbleYHighPos: Byte = 0
    @RamLocation(0xce) var sprObjectYPosition: Byte = 0
    @RamLocation(0xce) var playerYPosition: Byte = 0
    @RamLocation(0xcf) var enemyYPosition: Byte = 0
    @RamLocation(0xd5) var fireballYPosition: Byte = 0
    @RamLocation(0xd7) var blockYPosition: Byte = 0
    @RamLocation(0xdb) var miscYPosition: Byte = 0
    @RamLocation(0xe4) var bubbleYPosition: Byte = 0
    @RamLocation(0x3ad) var sprObjectRelXPos: Byte = 0
    @RamLocation(0x3ad) var playerRelXPos: Byte = 0
    @RamLocation(0x3ae) var enemyRelXPos: Byte = 0
    @RamLocation(0x3af) var fireballRelXPos: Byte = 0
    @RamLocation(0x3b0) var bubbleRelXPos: Byte = 0
    @RamLocation(0x3b1) var blockRelXPos: Byte = 0
    @RamLocation(0x3b3) var miscRelXPos: Byte = 0
    @RamLocation(0x3b8) var sprObjectRelYPos: Byte = 0
    @RamLocation(0x3b8) var playerRelYPos: Byte = 0
    @RamLocation(0x3b9) var enemyRelYPos: Byte = 0
    @RamLocation(0x3ba) var fireballRelYPos: Byte = 0
    @RamLocation(0x3bb) var bubbleRelYPos: Byte = 0
    @RamLocation(0x3bc) var blockRelYPos: Byte = 0
    @RamLocation(0x3be) var miscRelYPos: Byte = 0
    @RamLocation(0x3c4) var sprObjectSprAttrib: Byte = 0
    @RamLocation(0x3c4) var playerSprAttrib: Byte = 0
    @RamLocation(0x3c5) var enemySprAttrib: Byte = 0
    @RamLocation(0x400) var sprObjectXMoveForce: Byte = 0
    @RamLocation(0x401) var enemyXMoveForce: Byte = 0
    @RamLocation(0x416) var sprObjectYMFDummy: Byte = 0
    @RamLocation(0x416) var playerYMFDummy: Byte = 0
    @RamLocation(0x417) var enemyYMFDummy: Byte = 0
    @RamLocation(0x42c) var bubbleYMFDummy: Byte = 0
    @RamLocation(0x433) var sprObjectYMoveForce: Byte = 0
    @RamLocation(0x433) var playerYMoveForce: Byte = 0
    @RamLocation(0x434) var enemyYMoveForce: Byte = 0
    @RamLocation(0x43c) var blockYMoveForce: Byte = 0
    @RamLocation(0x716) var disableCollisionDet: Byte = 0
    @RamLocation(0x490) var playerCollisionBits: Byte = 0
    @RamLocation(0x491) var enemyCollisionBits: Byte = 0
    @RamLocation(0x499) var sprObjBoundBoxCtrl: Byte = 0
    @RamLocation(0x499) var playerBoundBoxCtrl: Byte = 0
    @RamLocation(0x49a) var enemyBoundBoxCtrl: Byte = 0
    @RamLocation(0x4a0) var fireballBoundBoxCtrl: Byte = 0
    @RamLocation(0x4a2) var miscBoundBoxCtrl: Byte = 0
    @RamLocation(0x6cb) var enemyFrenzyBuffer: Byte = 0
    @RamLocation(0x6cd) var enemyFrenzyQueue: Byte = 0
    @RamLocation(0xf) var enemyFlag: Byte = 0
    @RamLocation(0x16) val enemyID: ByteArray = ByteArray(0x23-0x16)
    @RamLocation(0x6d5) var playerGfxOffset: Byte = 0
    @RamLocation(0x700) var playerXSpeedAbsolute: Byte = 0
    @RamLocation(0x701) var frictionAdderHigh: Byte = 0
    @RamLocation(0x702) var frictionAdderLow: Byte = 0
    @RamLocation(0x703) var runningSpeed: Byte = 0
    @RamLocation(0x704) var swimmingFlag: Byte = 0
    @RamLocation(0x705) var playerXMoveForce: Byte = 0
    @RamLocation(0x706) var diffToHaltJump: Byte = 0
    @RamLocation(0x707) var jumpOriginYHighPos: Byte = 0
    @RamLocation(0x708) var jumpOriginYPosition: Byte = 0
    @RamLocation(0x709) var verticalForce: Byte = 0
    @RamLocation(0x70a) var verticalForceDown: Byte = 0
    @RamLocation(0x70b) var playerChangeSizeFlag: Byte = 0
    @RamLocation(0x70c) var playerAnimTimerSet: Byte = 0
    @RamLocation(0x70d) var playerAnimCtrl: Byte = 0
    @RamLocation(0x712) var deathMusicLoaded: Byte = 0
    @RamLocation(0x713) var flagpoleSoundQueue: Byte = 0
    @RamLocation(0x714) var crouchingFlag: Byte = 0
    @RamLocation(0x450) var maximumLeftSpeed: Byte = 0
    @RamLocation(0x456) var maximumRightSpeed: Byte = 0
    @RamLocation(0x3d0) var sprObjectOffscrBits: Byte = 0
    @RamLocation(0x3d0) var playerOffscreenBits: Byte = 0
    @RamLocation(0x3d1) var enemyOffscreenBits: Byte = 0
    @RamLocation(0x3d2) var fBallOffscreenBits: Byte = 0
    @RamLocation(0x3d3) var bubbleOffscreenBits: Byte = 0
    @RamLocation(0x3d4) var blockOffscreenBits: Byte = 0
    @RamLocation(0x3d6) var miscOffscreenBits: Byte = 0
    @RamLocation(0x3d8) var enemyOffscrBitsMasked: Byte = 0
    @RamLocation(0x46a) var cannonOffset: Byte = 0
    @RamLocation(0x46b) var cannonPageLoc: Byte = 0
    @RamLocation(0x471) var cannonXPosition: Byte = 0
    @RamLocation(0x477) var cannonYPosition: Byte = 0
    @RamLocation(0x47d) var cannonTimer: Byte = 0
    @RamLocation(0x46a) var whirlpoolOffset: Byte = 0
    @RamLocation(0x46b) var whirlpoolPageLoc: Byte = 0
    @RamLocation(0x471) var whirlpoolLeftExtent: Byte = 0
    @RamLocation(0x477) var whirlpoolLength: Byte = 0
    @RamLocation(0x47d) var whirlpoolFlag: Byte = 0
    @RamLocation(0x398) var vineFlagOffset: Byte = 0
    @RamLocation(0x399) var vineHeight: Byte = 0
    @RamLocation(0x39a) var vineObjOffset: Byte = 0
    @RamLocation(0x39d) var vineStartYPosition: Byte = 0
    @RamLocation(0x3e4) var blockOrigYPos: Byte = 0
    @RamLocation(0x3e6) var blockBBufLow: Byte = 0
    @RamLocation(0x3e8) var blockMetatile: Byte = 0
    @RamLocation(0x3ea) var blockPageLoc2: Byte = 0
    @RamLocation(0x3ec) var blockRepFlag: Byte = 0
    @RamLocation(0x3f0) var blockResidualCounter: Byte = 0
    @RamLocation(0x3f1) var blockOrigXPos: Byte = 0
    @RamLocation(0x4ac) var boundingBoxULXPos: Byte = 0
    @RamLocation(0x4ad) var boundingBoxULYPos: Byte = 0
    @RamLocation(0x4ae) var boundingBoxDRXPos: Byte = 0
    @RamLocation(0x4af) var boundingBoxDRYPos: Byte = 0
    @RamLocation(0x4ac) var boundingBoxULCorner: Byte = 0
    @RamLocation(0x4ae) var boundingBoxLRCorner: Byte = 0
    @RamLocation(0x4b0) var enemyBoundingBoxCoord: Byte = 0
    @RamLocation(0x39) var powerUpType: Byte = 0
    @RamLocation(0x3a) var fireballBouncingFlag: Byte = 0
    @RamLocation(0x6ce) var fireballCounter: Byte = 0
    @RamLocation(0x711) var fireballThrowingTimer: Byte = 0
    @RamLocation(0x6ae) var hammerEnemyOffset: Byte = 0
    @RamLocation(0x6b7) var jumpCoinMiscOffset: Byte = 0
    @RamLocation(0x500) var blockBuffer1: Byte = 0
    @RamLocation(0x5d0) var blockBuffer2: Byte = 0
    @RamLocation(0x3a2) var hammerThrowingTimer: Byte = 0
    @RamLocation(0x3c) var hammerBroJumpTimer: Byte = 0
    @RamLocation(0x6be) var miscCollisionFlag: Byte = 0
    @RamLocation(0x401) var redPTroopaOrigXPos: Byte = 0
    @RamLocation(0x58) var redPTroopaCenterYPos: Byte = 0
    @RamLocation(0xa0) var xMovePrimaryCounter: Byte = 0
    @RamLocation(0x58) var xMoveSecondaryCounter: Byte = 0
    @RamLocation(0x58) var cheepCheepMoveMFlag: Byte = 0
    @RamLocation(0x434) var cheepCheepOrigYPos: Byte = 0
    @RamLocation(0x6dd) var bitMFilter: Byte = 0
    @RamLocation(0x6d1) var lakituReappearTimer: Byte = 0
    @RamLocation(0x58) var lakituMoveSpeed: Byte = 0
    @RamLocation(0xa0) var lakituMoveDirection: Byte = 0
    @RamLocation(0x58) var firebarSpinStateLow: Byte = 0
    @RamLocation(0xa0) var firebarSpinStateHigh: Byte = 0
    @RamLocation(0x388) var firebarSpinSpeed: Byte = 0
    @RamLocation(0x34) var firebarSpinDirection: Byte = 0
    @RamLocation(0x6cf) var duplicateObjOffset: Byte = 0
    @RamLocation(0x6d3) var numberofGroupEnemies: Byte = 0
    @RamLocation(0xa0) var blooperMoveCounter: Byte = 0
    @RamLocation(0x58) var blooperMoveSpeed: Byte = 0
    @RamLocation(0x363) var bowserBodyControls: Byte = 0
    @RamLocation(0x364) var bowserFeetCounter: Byte = 0
    @RamLocation(0x365) var bowserMovementSpeed: Byte = 0
    @RamLocation(0x366) var bowserOrigXPos: Byte = 0
    @RamLocation(0x367) var bowserFlameTimerCtrl: Byte = 0
    @RamLocation(0x368) var bowserFrontOffset: Byte = 0
    @RamLocation(0x369) var bridgeCollapseOffset: Byte = 0
    @RamLocation(0x36a) var bowserGfxFlag: Byte = 0
    @RamLocation(0x483) var bowserHitPoints: Byte = 0
    @RamLocation(0x6dc) var maxRangeFromOrigin: Byte = 0
    @RamLocation(0x417) var bowserFlamePRandomOfs: Byte = 0
    @RamLocation(0x417) var piranhaPlantUpYPos: Byte = 0
    @RamLocation(0x434) var piranhaPlantDownYPos: Byte = 0
    @RamLocation(0x58) var piranhaPlantYSpeed: Byte = 0
    @RamLocation(0xa0) var piranhaPlantMoveFlag: Byte = 0
    @RamLocation(0x6d7) var fireworksCounter: Byte = 0
    @RamLocation(0x58) var explosionGfxCounter: Byte = 0
    @RamLocation(0xa0) var explosionTimerCounter: Byte = 0
    @RamLocation(0x7b3) var squ2NoteLenBuffer: Byte = 0
    @RamLocation(0x7b4) var squ2NoteLenCounter: Byte = 0
    @RamLocation(0x7b5) var squ2EnvelopeDataCtrl: Byte = 0
    @RamLocation(0x7b6) var squ1NoteLenCounter: Byte = 0
    @RamLocation(0x7b7) var squ1EnvelopeDataCtrl: Byte = 0
    @RamLocation(0x7b8) var triNoteLenBuffer: Byte = 0
    @RamLocation(0x7b9) var triNoteLenCounter: Byte = 0
    @RamLocation(0x7ba) var noiseBeatLenCounter: Byte = 0
    @RamLocation(0x7bb) var squ1SfxLenCounter: Byte = 0
    @RamLocation(0x7bd) var squ2SfxLenCounter: Byte = 0
    @RamLocation(0x7be) var sfxSecondaryCounter: Byte = 0
    @RamLocation(0x7bf) var noiseSfxLenCounter: Byte = 0
    @RamLocation(0xfa) var pauseSoundQueue: Byte = 0
    @RamLocation(0xff) var square1SoundQueue: Byte = 0
    @RamLocation(0xfe) var square2SoundQueue: Byte = 0
    @RamLocation(0xfd) var noiseSoundQueue: Byte = 0
    @RamLocation(0xfb) var areaMusicQueue: Byte = 0
    @RamLocation(0xfc) var eventMusicQueue: Byte = 0
    @RamLocation(0xf1) var square1SoundBuffer: Byte = 0
    @RamLocation(0xf2) var square2SoundBuffer: Byte = 0
    @RamLocation(0xf3) var noiseSoundBuffer: Byte = 0
    @RamLocation(0xf4) var areaMusicBuffer: Byte = 0
    @RamLocation(0x7b1) var eventMusicBuffer: Byte = 0
    @RamLocation(0x7b2) var pauseSoundBuffer: Byte = 0
    @RamLocation(0xf5) var musicData: Byte = 0
    @RamLocation(0xf5) var musicDataLow: Byte = 0
    @RamLocation(0xf6) var musicDataHigh: Byte = 0
    @RamLocation(0xf7) var musicOffsetSquare2: Byte = 0
    @RamLocation(0xf8) var musicOffsetSquare1: Byte = 0
    @RamLocation(0xf9) var musicOffsetTriangle: Byte = 0
    @RamLocation(0x7b0) var musicOffsetNoise: Byte = 0
    @RamLocation(0xf0) var noteLenLookupTblOfs: Byte = 0
    @RamLocation(0x7c0) var dACCounter: Byte = 0
    @RamLocation(0x7c1) var noiseDataLoopbackOfs: Byte = 0
    @RamLocation(0x7c4) var noteLengthTblAdder: Byte = 0
    @RamLocation(0x7c5) var areaMusicBufferAlt: Byte = 0
    @RamLocation(0x7c6) var pauseModeFlag: Byte = 0
    @RamLocation(0x7c7) var groundMusicHeaderOfs: Byte = 0
    @RamLocation(0x7ca) var altRegContentFlag: Byte = 0

}