// by Claude - TAS replay test: runs happylee-warps TAS through the translated Kotlin code
// and verifies game progression by comparing against FCEUX RAM dumps.
package com.ivieleague.smbtranslation.interpreter

import com.ivieleague.smbtranslation.*
import com.ivieleague.smbtranslation.nes.PpuRenderer
import com.ivieleague.smbtranslation.utils.*
import org.jetbrains.skia.EncodedImageFormat
import org.jetbrains.skia.Surface
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.Timeout
import java.io.File
import java.nio.file.Files
import java.nio.file.Path
import java.util.concurrent.TimeUnit
import kotlin.test.assertTrue

/**
 * Replays a TAS through the translated Kotlin code with full per-frame FCEUX RAM sync.
 * Each frame: sync all state from FCEUX dump, inject next frame's buttons, run full NMI, compare outputs.
 *
 * The FCEUX dump is generated by dump-all-ram.lua using emu.registerafter(), which captures
 * state AFTER the entire frame completes — including the NMI handler which calls
 * operModeExecutionTree(). So dump[n] = state after NMI n processed input[n].
 * To produce dump[n+1] from dump[n], we run a full nonMaskableInterrupt() with input[n+1].
 */
class TASReplayTest {

    companion object {
        const val OPER_MODE = 0x0770
        const val OPER_MODE_TASK = 0x0772
        const val FRAME_COUNTER = 0x09
        const val WORLD_NUMBER = 0x075F
        const val LEVEL_NUMBER = 0x0760
        const val PLAYER_X_POSITION = 0x0086
        const val PLAYER_Y_POSITION = 0x00CE
        const val GAME_ENGINE_SUBROUTINE = 0x0E
        const val SCREEN_ROUTINE_TASK = 0x073C

        // NMI suppress frames: RESET handler still running
        val SUPPRESS_NMI_FRAMES = setOf(0, 1, 2, 3, 4, 6, 7)

        // Addresses excluded from comparison. Now that we run the full NMI,
        // most NMI-bookkeeping differences are modeled. Remaining exclusions are
        // for areas using Kotlin types that don't map to flat bytes (VRAM buffers,
        // stack) or hardware-level concerns (OAM DMA, PPU registers).
        val EXCLUDED_ADDRESSES: Set<Int> = buildSet {
            addAll(0x00..0x0D)                     // zero-page scratch ($00-$08 temp vars, $09 frameCounter,
                                                    // $0A-$0D joypad/button processing intermediates)
            addAll(0xE7..0xEF)                     // ROM data pointers ($E7-$EA) + scratch ($EB-$EF)
            addAll(0xF0..0xFF)                     // sound queues + audio buffers — soundEngine stub differs
            addAll(0x100..0x1FF)                   // NES stack page — Kotlin uses custom Stack object
            addAll(0x200..0x2FF)                    // OAM sprites — Kotlin uses Sprite objects, not flat bytes
            addAll(0x300..0x3AC)                    // VRAM buffer 1 — Kotlin uses MutableVBuffer (ArrayList)
            addAll(0x3AD..0x3D0)                    // VRAM buffer 1 overflow zone — NES physically overflows
                                                    // into relXPos/relYPos/sprAttrib/offscrBits when buffer
                                                    // exceeds $AC bytes; Kotlin ArrayList doesn't overflow
            // VRAM Buffer 2 overflow: NES buffer starts at $0341 and can overflow into game
            // state RAM when rendering data exceeds buffer capacity. Kotlin uses ArrayList
            // which doesn't overflow. These specific addresses diverge at frame 28+:
            //   $03D3 = offscrBits[3],     $03ED = blockRepFlags[1],
            //   $03F0 = blockResidualCounter,
            //   $0402 = sprObjXMoveForce[2], $0403 = sprObjXMoveForce[3],
            //   $0418 = sprObjYMFDummy[2], $0419 = sprObjYMFDummy[3],
            //   $042C = sprObjYMFDummy[22],
            //   $0435 = sprObjYMoveForce[2], $0436 = sprObjYMoveForce[3]
            addAll(intArrayOf(0x03D3, 0x03ED, 0x03F0, 0x0402, 0x0403, 0x0418, 0x0419, 0x042C, 0x0435, 0x0436).toList())
            add(0x00E3)                                // sprObjYPos[21] — unused slot between misc(13-16) and
                                                        // bubbles(22-24), stale NES data from VRAM overflow
            addAll(0x4AC..0x4FF)                    // bounding box coords — transient collision workspace
            addAll(0x500..0x7FF)                    // block buffers, VRAM buf 2, display digits, sound,
                                                    // sprite shuffler, joypad bits, timerControl,
                                                    // vRAMBufferAddrCtrl, pause status, mirror PPU regs,
                                                    // intervalTimerControl, timers, pseudoRandomBitReg
        }

        val COVERED_ADDRESSES: Set<Int> get() = GameRamMapper.coveredAddresses
        val BOOLEAN_ADDRESSES: Set<Int> get() = GameRamMapper.booleanAddresses
    }

    data class FrameInput(val player1: Int, val player2: Int = 0)

    private fun parseFM2(file: File): List<FrameInput> {
        val inputs = mutableListOf<FrameInput>()
        for (line in file.readLines()) {
            if (!line.startsWith("|")) continue
            val parts = line.removePrefix("|").removeSuffix("|").split("|")
            if (parts.size < 2) continue
            val p1 = parseFM2Buttons(parts[1].padEnd(8, '.'))
            val p2 = if (parts.size >= 3) parseFM2Buttons(parts[2].padEnd(8, '.')) else 0
            inputs.add(FrameInput(p1, p2))
        }
        return inputs
    }

    private fun parseFM2Buttons(input: String): Int {
        var buttons = 0
        if (input.length >= 8) {
            if (input[0] != '.') buttons = buttons or 0x01
            if (input[1] != '.') buttons = buttons or 0x02
            if (input[2] != '.') buttons = buttons or 0x04
            if (input[3] != '.') buttons = buttons or 0x08
            if (input[4] != '.') buttons = buttons or 0x10
            if (input[5] != '.') buttons = buttons or 0x20
            if (input[6] != '.') buttons = buttons or 0x40
            if (input[7] != '.') buttons = buttons or 0x80
        }
        return buttons
    }

    private fun findFile(vararg paths: String): File? =
        paths.map { File(it) }.firstOrNull { it.exists() }

    // Reverse lookup: ROM address → index in RomData arrays
    private val enemyAddrToIdx: Map<Int, Int> = RomData.enemyDataAddresses
        .mapIndexed { idx, addr -> addr to idx }.toMap()
    private val areaAddrToIdx: Map<Int, Int> = RomData.areaDataAddresses
        .mapIndexed { idx, addr -> addr to idx }.toMap()
    // NES advances AreaData pointer by 2 past the header (see getAreaDataAddrs assembly).
    // Build a lookup for base+2 addresses, and pre-compute headerless arrays so that
    // NES offsets work directly (they're relative to the advanced pointer).
    private val areaAddrPlus2ToIdx: Map<Int, Int> = RomData.areaDataAddresses
        .mapIndexed { idx, addr -> (addr + 2) to idx }.toMap()
    private val areaDataHeaderless: Array<ByteArray> = RomData.areaDataArrays
        .map { if (it.size > 2) it.copyOfRange(2, it.size) else it }.toTypedArray()
    
    private fun snapshot(system: System, name: String) {
        val scale = 2
        val surface = Surface.makeRasterN32Premul(256 * scale, 240 * scale)
        PpuRenderer.render(surface.canvas, system.ppu, scale, scrollStartY = 16)
        val data = surface.makeImageSnapshot().encodeToData(EncodedImageFormat.PNG)
            ?: error("Failed to encode PNG")
        val outPath = Path.of("build", "screenshots", "$name.png")
        Files.createDirectories(outPath.parent)
        Files.write(outPath, data.bytes)
    }

    private fun syncFullRamFromFceux(system: System, fceuxFrame: ByteArray, offset: Int) {
        GameRamMapper.fromFlat(system.ram, fceuxFrame, offset)
        system.ram.stack.clear()
        // VRAM buffers are MutableVBuffer (custom type) — not synced by GameRamMapper.
        // FCEUX dump captures state after NMI consumed+cleared the buffers, so clear them.
        system.ram.vRAMBuffer1.clear()
        system.ram.vRAMBuffer2.clear()

        // Reconstruct Kotlin-only ByteArray references from ROM pointer bytes.
        // The NES uses indirect pointers at $E9/$EA (enemy data) and $E7/$E8 (area data)
        // to read ROM. Kotlin uses ByteArray references instead. Reconstruct them from
        // the synced pointer bytes so enemy spawning and area parsing work correctly.
        val enemyAddr = (system.ram.enemyDataLow.toInt() and 0xFF) or
                ((system.ram.enemyDataHigh.toInt() and 0xFF) shl 8)
        val enemyIdx = enemyAddrToIdx[enemyAddr]
        if (enemyIdx != null) {
            system.ram.enemyDataBytes = RomData.enemyDataArrays[enemyIdx]
        }

        // NES advances the AreaData pointer ($E7/$E8) by 2 past the 2-byte header
        // (see getAreaDataAddrs assembly: clc/adc #$02/sta AreaDataLow).
        // Kotlin keeps the base address and uses areaDataOffset=2 to skip the header.
        // FCEUX dump has $E7/$E8 = base+2, with ALL offsets relative to base+2.
        // Use headerless arrays (header stripped) so NES offsets work directly.
        val areaAddr = (system.ram.areaDataLow.toInt() and 0xFF) or
                ((system.ram.areaDataHigh.toInt() and 0xFF) shl 8)
        val areaIdx = areaAddrToIdx[areaAddr]
        if (areaIdx != null) {
            // Exact base match — use full array (Kotlin's normal mode with offset=2)
            system.ram.areaData = RomData.areaDataArrays[areaIdx]
        } else {
            // Try base+2 match (NES advanced pointer past header)
            val idx2 = areaAddrPlus2ToIdx[areaAddr]
            if (idx2 != null) {
                // Use headerless array so all synced offsets (areaDataOffset,
                // areaObjOffsetBuffer, etc.) work correctly without adjustment
                system.ram.areaData = areaDataHeaderless[idx2]
            }
        }
    }

    private fun initializeFromInterpreter(system: System, romFile: File): SubroutineComparison {
        val comparison = SubroutineComparison.create(romFile.path)
        val interp = comparison.interpreter

        var ppuStatus: UByte = 0x80u
        var ppuStatusReads = 0

        interp.memoryReadHook = { addr ->
            when (addr) {
                0x2002 -> {
                    ppuStatusReads++
                    val status = ppuStatus
                    ppuStatus = ppuStatus and 0x7Fu
                    if (ppuStatusReads % 100 == 0) ppuStatus = ppuStatus or 0x80u
                    status
                }
                in 0x2000..0x2007 -> 0u
                else -> null
            }
        }
        interp.memoryWriteHook = { addr, _ ->
            when (addr) {
                0x2000 -> true
                in 0x2001..0x2007 -> true
                0x4014 -> true
                in 0x4000..0x4017 -> true
                else -> false
            }
        }

        interp.cpu.PC = 0x8000u
        var cycles = 0
        while (cycles < 100000) {
            val pc = interp.cpu.PC.toInt()
            val opcode = interp.memory.readByte(pc).toInt()
            if (opcode == 0x4C) {
                val lo = interp.memory.readByte(pc + 1).toInt()
                val hi = interp.memory.readByte(pc + 2).toInt()
                val target = lo or (hi shl 8)
                if (target == pc) break
            }
            interp.step()
            cycles++
        }
        println("RESET done in $cycles steps")

        ppuStatus = 0x80u
        ppuStatusReads = 0
        interp.cpu.PC = 0x8082u
        cycles = 0
        while (cycles < 50000) {
            if (interp.memory.readByte(interp.cpu.PC.toInt()) == 0x40.toUByte()) break
            interp.step()
            cycles++
        }
        println("First NMI done in $cycles steps")

        comparison.syncRamToSystem(system)

        interp.memoryReadHook = null
        interp.memoryWriteHook = null

        return comparison
    }

    @Timeout(value = 120, unit = TimeUnit.SECONDS)
    @Test
    fun `TAS replay reaches game completion`() {
        val romFile = findFile("smb.nes", "../smb.nes")
        if (romFile == null) { println("Skipping: No ROM file found"); return }

        val tasFile = findFile(
            "happylee-warps.fm2", "../happylee-warps.fm2",
            "/Users/jivie/Projects/smb-translation/happylee-warps.fm2"
        )
        if (tasFile == null) { println("Skipping: No TAS file found"); return }

        val fceuxRamFile = findFile(
            "data/tas/fceux-full-ram.bin", "../data/tas/fceux-full-ram.bin",
            "/Users/jivie/Projects/smb-translation/fceux-full-ram.bin",
            "/Users/jivie/Projects/smb-translation/old-tas-info/fceux-full-ram.bin"
        )
        val fceuxRam = fceuxRamFile?.readBytes()
        val comparisonMode = fceuxRam != null

        println("=== TAS Replay Test ===")
        println("ROM: ${romFile.absolutePath}")
        println("TAS: ${tasFile.absolutePath}")
        if (fceuxRam != null) {
            println("FCEUX RAM dump: ${fceuxRam.size / 2048} frames")
            println("Comparison mode: ON (full NMI)")
        } else {
            println("WARNING: No FCEUX RAM dump — fallback to full NMI, no comparison")
            println("Comparison mode: OFF (running open-loop)")
        }

        val tasInputs = parseFM2(tasFile)
        println("Loaded ${tasInputs.size} TAS frames")

        val system = System()
        initializeFromInterpreter(system, romFile)

        var maxWorld = 1
        var maxLevel = 1
        var reachedW84 = false
        var gameCompleted = false
        var lastProgressFrame = 0
        var nmiErrorCount = 0
        val errorLocations = mutableMapOf<String, Int>()
        val totalFrames = minOf(tasInputs.size, if (fceuxRam != null) fceuxRam.size / 2048 else tasInputs.size)

        // Divergence tracking
        val addrDivergenceCount = IntArray(2048)
        var framesWithErrors = 0
        var totalDivergences = 0
        var comparedFrames = 0
        var lagFramesSkipped = 0
        // Track first divergence frame for each address
        val firstDivFrame = mutableMapOf<Int, Int>()
        // Top addresses to watch with detailed logging
        val WATCHED_ADDRS = setOf(0x0018, 0x0019, 0x001A, 0x00D4, 0x00A1, 0x00D0, 0x001F, 0x0016, 0x0011, 0x0048, 0x049C, 0x0023, 0x0088, 0x000E, 0x0033)
        var watchedDivsLogged = 0

        println("\n=== Running TAS ($totalFrames frames) ===")

        for (frame in 0 until totalFrames) {
            if (frame in SUPPRESS_NMI_FRAMES) continue

            // Full RAM sync from FCEUX dump.
            // dump[n] = state after NMI n (including operModeExecutionTree) via emu.registerafter().
            // To produce dump[n+1], we run a full NMI with input[n+1].
            if (fceuxRam != null) {
                val fOff = frame * 2048
                if (fOff + 2047 < fceuxRam.size) {
                    syncFullRamFromFceux(system, fceuxRam, fOff)
                }
            }

            // Set joypad input for the NEXT frame's NMI.
            // dump[frame] was produced using input[frame]. To get dump[frame+1],
            // we need input[frame+1].
            val nextInput = if (frame + 1 < tasInputs.size) tasInputs[frame + 1].player1 else 0
            system.inputs.joypadPort1 = JoypadBits(nextInput.toByte())

            // Debug dump for enemy spawning at first divergence frame
            if (frame == 3541 && fceuxRam != null) {
                val fOff = frame * 2048
                fun hex(b: Int) = (b and 0xFF).toString(16).padStart(2, '0')
                println("\n=== Frame $frame AREA PARSER DEBUG ===")
                // Area parser control variables from FCEUX dump (= Kotlin start state after sync)
                println("  vRAMBufferAddrCtrl (\$0773): ${hex(fceuxRam[fOff + 0x773].toInt())}")
                println("  areaParserTaskNum (\$071F): ${hex(fceuxRam[fOff + 0x71F].toInt())}")
                println("  scrollThirtyTwo (\$073F): ${hex(fceuxRam[fOff + 0x73F].toInt())}")
                println("  blockRepFlags (\$0130-1): [0]=${hex(fceuxRam[fOff + 0x130].toInt())}, [1]=${hex(fceuxRam[fOff + 0x131].toInt())}")
                // Area data pointer
                val aLo = fceuxRam[fOff + 0xE7].toInt() and 0xFF
                val aHi = fceuxRam[fOff + 0xE8].toInt() and 0xFF
                val areaAddr = aLo or (aHi shl 8)
                println("  AreaData ptr (\$E7/\$E8): \$${hex(aHi)}${hex(aLo)} → idx=${areaAddrToIdx[areaAddr]}")
                println("  areaDataOffset (\$072C): ${hex(fceuxRam[fOff + 0x72C].toInt())}")
                println("  currentPageLoc (\$0725): ${hex(fceuxRam[fOff + 0x725].toInt())}")
                println("  currentColumnPos (\$0726): ${hex(fceuxRam[fOff + 0x726].toInt())}")
                println("  ScreenLeft_PageLoc (\$071A): ${hex(fceuxRam[fOff + 0x071A].toInt())}")
                println("  ScreenRight_PageLoc (\$071C): ${hex(fceuxRam[fOff + 0x071C].toInt())}")
                println("  areaNumber (\$074E): ${hex(fceuxRam[fOff + 0x74E].toInt())}")
                println("  worldNumber (\$075F): ${hex(fceuxRam[fOff + 0x75F].toInt())}")
                println("  Kotlin areaData null? ${system.ram.areaData == null}")
                println("  Kotlin areaData size: ${system.ram.areaData?.size}")
                // Enemy state
                println("  Enemy flags: ${(0..4).map { "[$it]=${hex(system.ram.enemyFlags[it].toInt())}" }}")
                println("  Enemy IDs:   ${(0..4).map { "[$it]=${hex(system.ram.enemyID[it].toInt())}" }}")
            }

            // Debug dump for $00D0/$00D4 divergence (enemy Y positions, first@7037/7039)
            if (frame in 7035..7045 && fceuxRam != null) {
                val fOff = frame * 2048
                val nextOff = (frame + 1) * 2048
                fun hex(b: Int) = (b and 0xFF).toString(16).padStart(2, '0')
                if (nextOff + 2047 < fceuxRam.size) {
                    val kFlat = GameRamMapper.toFlat(system.ram)
                    val d4k = kFlat[0xD4].toInt() and 0xFF
                    val d4f = fceuxRam[nextOff + 0xD4].toInt() and 0xFF
                    val d0k = kFlat[0xD0].toInt() and 0xFF
                    val d0f = fceuxRam[nextOff + 0xD0].toInt() and 0xFF
                    val a1k = kFlat[0xA1].toInt() and 0xFF
                    val a1f = fceuxRam[nextOff + 0xA1].toInt() and 0xFF
                    if (d4k != d4f || d0k != d0f || a1k != a1f) {
                        println("\n=== Frame $frame ENEMY Y DEBUG ===")
                        println("  sprObjYPos[2] (\$D0): kotlin=${hex(d0k)} fceux=${hex(d0f)}")
                        println("  sprObjYPos[6] (\$D4): kotlin=${hex(d4k)} fceux=${hex(d4f)}")
                        println("  sprObjYSpeed[2] (\$A1): kotlin=${hex(a1k)} fceux=${hex(a1f)}")
                        // Context: enemy states and IDs for slots 1 and 5
                        println("  enemyState[1] (\$1F): ${hex(fceuxRam[fOff + 0x1F].toInt())}")
                        println("  enemyState[5] (\$23): ${hex(fceuxRam[fOff + 0x23].toInt())}")
                        println("  enemyID[1]: ${hex(fceuxRam[fOff + 0x17].toInt())}")
                        println("  enemyID[5]: ${hex(fceuxRam[fOff + 0x1B].toInt())}")
                        println("  enemyFlags[1]: ${hex(fceuxRam[fOff + 0x10].toInt())}")
                        println("  enemyFlags[5]: ${hex(fceuxRam[fOff + 0x14].toInt())}")
                        println("  gameEngineSubroutine: ${hex(fceuxRam[fOff + 0x0E].toInt())}")
                        println("  operMode: ${hex(fceuxRam[fOff + 0x770].toInt())}")
                    }
                }
            }

            // Debug dump for $00A1/$001F divergence (enemy slot 1, first@9064)
            if (frame in 9060..9070 && fceuxRam != null) {
                val fOff = frame * 2048
                val nextOff = (frame + 1) * 2048
                fun hex(b: Int) = (b and 0xFF).toString(16).padStart(2, '0')
                if (nextOff + 2047 < fceuxRam.size) {
                    val kFlat = GameRamMapper.toFlat(system.ram)
                    val a1k = kFlat[0xA1].toInt() and 0xFF
                    val a1f = fceuxRam[nextOff + 0xA1].toInt() and 0xFF
                    val f1k = kFlat[0x1F].toInt() and 0xFF
                    val f1f = fceuxRam[nextOff + 0x1F].toInt() and 0xFF
                    // Always print for frame 9064 and nearby
                    if (frame in 9062..9066 || a1k != a1f || f1k != f1f) {
                        println("\n=== Frame $frame ENEMY SLOT1 DEBUG ===")
                        println("  PRE-NMI (synced from FCEUX[$frame]):")
                        println("    enemyID[1]=${ hex(fceuxRam[fOff + 0x17].toInt()) } enemyFlags[1]=${ hex(fceuxRam[fOff + 0x10].toInt()) } enemyState[1]=${ hex(fceuxRam[fOff + 0x1F].toInt()) }")
                        println("    sprObjXPos[2]=${ hex(fceuxRam[fOff + 0x88].toInt()) } sprObjYPos[2]=${ hex(fceuxRam[fOff + 0xD0].toInt()) } sprObjPageLoc[2]=${ hex(fceuxRam[fOff + 0x6F].toInt()) }")
                        println("    sprObjYSpeed[2]=${ hex(fceuxRam[fOff + 0xA1].toInt()) } sprObjXSpeed[2]=${ hex(fceuxRam[fOff + 0x59].toInt()) }")
                        println("    sprObjYHighPos[2]=${ hex(fceuxRam[fOff + 0xB7].toInt()) } sprObjYMoveForce[2]=${ hex(fceuxRam[fOff + 0x435].toInt()) }")
                        println("    gameEngineSubroutine=${ hex(fceuxRam[fOff + 0x0E].toInt()) } timerControl=${ hex(fceuxRam[fOff + 0x747].toInt()) }")
                        println("    screenLeftPageLoc=${ hex(fceuxRam[fOff + 0x71A].toInt()) } screenRightPageLoc=${ hex(fceuxRam[fOff + 0x71C].toInt()) }")
                        // Compute block buffer tile that ChkUnderEnemy would read
                        val objX = fceuxRam[fOff + 0x88].toInt() and 0xFF
                        val objY = fceuxRam[fOff + 0xD0].toInt() and 0xFF
                        val pageLoc = fceuxRam[fOff + 0x6F].toInt() and 0xFF
                        val xAdder = 0x08  // blockBufferXAdder2[0x15]
                        val yAdder = 0x18  // blockBufferYAdder2[0x15]
                        val modifiedX = (objX + xAdder) and 0xFF
                        val xCarry = if (objX + xAdder > 0xFF) 1 else 0
                        val pageWithCarry = (pageLoc + xCarry) and 0x01
                        val columnIndex = (pageWithCarry shl 4) or (modifiedX ushr 4)
                        val useBuf2 = (columnIndex and 0x10) != 0
                        val col = columnIndex and 0x0F
                        val modifiedY = (objY + yAdder) and 0xFF
                        val vertOffset = ((modifiedY and 0xF0) - 0x20) and 0xFF
                        val bufIndex = col + vertOffset
                        // Read tile from synced block buffers
                        val buf = if (useBuf2) system.ram.blockBuffer2 else system.ram.blockBuffer1
                        val tile = if (bufIndex in buf.indices) buf[bufIndex].toInt() and 0xFF else -1
                        // Also read from FCEUX dump directly
                        val fceuxBufBase = if (useBuf2) 0x5D0 else 0x500
                        val fceuxTile = fceuxRam[fOff + fceuxBufBase + bufIndex].toInt() and 0xFF
                        println("    BB check: objX=${ hex(objX) } objY=${ hex(objY) } page=$pageLoc col=$col vertOfs=${ hex(vertOffset) } bufIdx=$bufIndex buf${if(useBuf2) 2 else 1}")
                        println("    BB tile: kotlin=${hex(tile)} fceux=${hex(fceuxTile)} (addr=\$${ hex(fceuxBufBase + bufIndex) })")
                        // SubtEnemyYPos check
                        val subtResult = (objY + 0x3E) and 0xFF
                        println("    subtEnemyYPos: Y+3E=${hex(subtResult)} >= 44? ${subtResult >= 0x44}")
                        println("  POST-NMI comparison (kotlin vs FCEUX[${ frame + 1 }]):")
                        println("    sprObjYSpeed[2]: kotlin=${hex(a1k)} fceux=${hex(a1f)}")
                        println("    enemyState[1]: kotlin=${hex(f1k)} fceux=${hex(f1f)}")
                        println("    sprObjYPos[2]: kotlin=${hex(kFlat[0xD0].toInt() and 0xFF)} fceux=${hex(fceuxRam[nextOff + 0xD0].toInt() and 0xFF)}")
                        // Also check flags and ID post-NMI
                        println("    enemyFlags[1]: kotlin=${hex(kFlat[0x10].toInt() and 0xFF)} fceux=${hex(fceuxRam[nextOff + 0x10].toInt() and 0xFF)}")
                        println("    enemyID[1]: kotlin=${hex(kFlat[0x17].toInt() and 0xFF)} fceux=${hex(fceuxRam[nextOff + 0x17].toInt() and 0xFF)}")
                        println("    sprObjXSpeed[2] (\$59): kotlin=${hex(kFlat[0x59].toInt() and 0xFF)} fceux=${hex(fceuxRam[nextOff + 0x59].toInt() and 0xFF)}")
                        println("    enemyMovingDirs[1] (\$47): kotlin=${hex(kFlat[0x47].toInt() and 0xFF)} fceux=${hex(fceuxRam[nextOff + 0x47].toInt() and 0xFF)}")
                        println("    playerXPos (\$86): kotlin=${hex(kFlat[0x86].toInt() and 0xFF)} fceux=${hex(fceuxRam[nextOff + 0x86].toInt() and 0xFF)}")
                        println("    playerPageLoc (\$6D): kotlin=${hex(kFlat[0x6D].toInt() and 0xFF)} fceux=${hex(fceuxRam[nextOff + 0x6D].toInt() and 0xFF)}")
                    }
                }
            }

            // Debug dump for W4-1 enemy cascade divergence ($0018-$001a)
            if (frame in 4619..4622 && fceuxRam != null) {
                val fOff = frame * 2048
                fun hex(b: Int) = (b and 0xFF).toString(16).padStart(2, '0')
                println("\n=== Frame $frame W4-1 ENEMY CASCADE DEBUG ===")
                println("  Enemy IDs:    ${(0..5).map { "[$it]=${hex(fceuxRam[fOff + 0x16 + it].toInt())}" }}")
                println("  Enemy flags:  ${(0..5).map { "[$it]=${hex(fceuxRam[fOff + 0x0F + it].toInt())}" }}")
                println("  Enemy states: ${(0..5).map { "[$it]=${hex(fceuxRam[fOff + 0x1E + it].toInt())}" }}")
                println("  enemyFrenzyBuffer (\$06CB): ${hex(fceuxRam[fOff + 0x6CB].toInt())}")
                println("  enemyFrenzyQueue (\$06CD): ${hex(fceuxRam[fOff + 0x6CD].toInt())}")
                println("  enemyDataOffset (\$0739): ${hex(fceuxRam[fOff + 0x739].toInt())}")
                println("  enemyObjectPageLoc (\$073A): ${hex(fceuxRam[fOff + 0x73A].toInt())}")
                println("  enemyObjectPageSel (\$073B): ${hex(fceuxRam[fOff + 0x73B].toInt())}")
                println("  screenRightPageLoc (\$071C): ${hex(fceuxRam[fOff + 0x71C].toInt())}")
                println("  screenRightXPos (\$071E): ${hex(fceuxRam[fOff + 0x71E].toInt())}")
                println("  areaParserTaskNum (\$071F): ${hex(fceuxRam[fOff + 0x71F].toInt())}")
                println("  frenzyEnemyTimer (\$06CE): ${hex(fceuxRam[fOff + 0x6CE].toInt())}")
                println("  lakituReappearTimer (\$06D1): ${hex(fceuxRam[fOff + 0x6D1].toInt())}")
                // Enemy data pointer and lookup validation
                val edLow = fceuxRam[fOff + 0xE9].toInt() and 0xFF
                val edHigh = fceuxRam[fOff + 0xEA].toInt() and 0xFF
                val edAddr = edLow or (edHigh shl 8)
                println("  EnemyData ptr (\$E9/\$EA): \$${edAddr.toString(16).padStart(4, '0')}")
                val lookupResult = enemyAddrToIdx[edAddr]
                println("  enemyAddrToIdx lookup: ${lookupResult?.let { "idx=$it" } ?: "NULL (not found!)"}")
                // Dump enemy data from offset 0 AND from current offset
                val edOffset = fceuxRam[fOff + 0x739].toInt() and 0xFF
                val enemyData = system.ram.enemyDataBytes
                if (enemyData != null) {
                    val allBytes = (0 until minOf(enemyData.size, 20)).map { i -> hex(enemyData[i].toInt()) }
                    println("  enemyData[0..${minOf(enemyData.size, 20)-1}]: ${allBytes.joinToString(" ")}")
                    val bytes = (0..15).map { i -> hex(enemyData.getOrElse(edOffset + i) { 0xFF.toByte() }.toInt()) }
                    println("  enemyData[@$edOffset..+15]: ${bytes.joinToString(" ")}")
                    println("  enemyData total size: ${enemyData.size}")
                } else {
                    println("  enemyDataBytes is NULL!")
                }
                println("  Kotlin enemyIDs: ${(0..5).map { "[$it]=${hex(system.ram.enemyID[it].toInt())}" }}")
                println("  Kotlin enemyFlags: ${(0..5).map { "[$it]=${hex(system.ram.enemyFlags[it].toInt())}" }}")
            }
            // Post-NMI dump for frame 4621
            val doPostDump4621 = frame == 4621 && fceuxRam != null
            // Enable enemy trace for frame 9064
            system.debugEnemyTrace = frame == 9064
            // Run full NMI (includes joypads, timers, PRNG, pause, AND operModeExecutionTree)
            var runError: Throwable? = null
            try {
                val thread = Thread {
                    try {
                        system.nonMaskableInterrupt()
                    } catch (e: Throwable) {
                        runError = e
                    }
                }
                thread.start()
                thread.join(2000)
                if (thread.isAlive) {
                    println("Frame $frame HUNG! Mode=${system.ram.operMode}, Task=${system.ram.operModeTask}")
                    @Suppress("DEPRECATION")
                    thread.stop()
                    nmiErrorCount++
                    continue
                }
            } catch (e: Exception) {
                runError = e
            }

            if (runError != null) {
                nmiErrorCount++
                val loc = runError!!.stackTrace.firstOrNull {
                    it.className.startsWith("com.ivieleague.smbtranslation")
                }?.let { "${it.fileName}:${it.lineNumber}" } ?: "unknown"
                errorLocations[loc] = (errorLocations[loc] ?: 0) + 1
                if (nmiErrorCount <= 5 || frame % 2000 == 0) {
                    println("Frame $frame ERROR #$nmiErrorCount: ${runError!!::class.simpleName}: ${runError!!.message}")
                    println(runError!!.stackTraceToString().lines().take(5).joinToString("\n"))
                }
            }

            if (frame % 500 == 0) {
                val msg = "Frame $frame: World=${system.ram.worldNumber + 1}-${system.ram.levelNumber + 1}, Mode=${system.ram.operMode}, Task=${system.ram.operModeTask}, X=${system.ram.playerXPosition}"
                println(msg)
            }

            if (frame % 60 == 0) {
                snapshot(system, "tas-frame-${"%05d".format(frame)}")
            }

            // Post-NMI dump for frame 4621
            if (doPostDump4621 && runError == null) {
                fun hex(b: Int) = (b and 0xFF).toString(16).padStart(2, '0')
                println("\n=== Frame 4621 POST-NMI STATE ===")
                println("  Kotlin enemyIDs:    ${(0..5).map { "[$it]=${hex(system.ram.enemyID[it].toInt())}" }}")
                println("  Kotlin enemyFlags:  ${(0..5).map { "[$it]=${hex(system.ram.enemyFlags[it].toInt())}" }}")
                println("  Kotlin enemyStates: ${(0..5).map { "[$it]=${hex(system.ram.enemyState[it].toInt())}" }}")
                println("  enemyDataOffset: ${hex(system.ram.enemyDataOffset.toInt())}")
                println("  enemyFrenzyBuffer: ${hex(system.ram.enemyFrenzyBuffer.toInt())}")
                println("  frenzyEnemyTimer: ${hex(system.ram.frenzyEnemyTimer.toInt())}")
                println("  lakituReappearTimer: ${hex(system.ram.lakituReappearTimer.toInt())}")
                println("  enemyObjectPageLoc: ${hex(system.ram.enemyObjectPageLoc.toInt())}")
                println("  enemyObjectPageSel: ${hex(system.ram.enemyObjectPageSel.toInt())}")
                // Also dump FCEUX next-frame state for direct comparison
                val nextOff2 = (frame + 1) * 2048
                if (nextOff2 + 2047 < fceuxRam!!.size) {
                    println("  FCEUX  enemyIDs:    ${(0..5).map { "[$it]=${hex(fceuxRam[nextOff2 + 0x16 + it].toInt())}" }}")
                    println("  FCEUX  enemyFlags:  ${(0..5).map { "[$it]=${hex(fceuxRam[nextOff2 + 0x0F + it].toInt())}" }}")
                    println("  FCEUX  enemyStates: ${(0..5).map { "[$it]=${hex(fceuxRam[nextOff2 + 0x1E + it].toInt())}" }}")
                    println("  FCEUX  enemyDataOffset: ${hex(fceuxRam[nextOff2 + 0x739].toInt())}")
                    println("  FCEUX  frenzyBuffer: ${hex(fceuxRam[nextOff2 + 0x6CB].toInt())}")
                    println("  FCEUX  frenzyTimer: ${hex(fceuxRam[nextOff2 + 0x6CE].toInt())}")
                    println("  FCEUX  lakituReappear: ${hex(fceuxRam[nextOff2 + 0x6D1].toInt())}")
                }
            }

            // Compare Kotlin output against next frame's FCEUX golden state
            if (comparisonMode && runError == null) {
                val nextOff = (frame + 1) * 2048
                if (nextOff + 2047 < fceuxRam!!.size && frame + 1 !in SUPPRESS_NMI_FRAMES) {
                    val kotlinFlat = GameRamMapper.toFlat(system.ram)
                    val diffs = mutableListOf<Triple<Int, Int, Int>>() // (addr, kotlinVal, fceuxVal)
                    for (addr in 0 until 2048) {
                        if (addr in EXCLUDED_ADDRESSES || addr !in COVERED_ADDRESSES) continue
                        var kv = kotlinFlat[addr].toInt() and 0xFF
                        var fv = fceuxRam[nextOff + addr].toInt() and 0xFF
                        if (addr in BOOLEAN_ADDRESSES) {
                            kv = if (kv != 0) 1 else 0
                            fv = if (fv != 0) 1 else 0
                        }
                        if (kv != fv) diffs.add(Triple(addr, kv, fv))
                    }

                    // Lag frame detection: NMI took >1 VBlank, FCEUX captured mid-initializeMemory.
                    // Signature: source dump has Task=0, Kotlin output cleared RAM (task incremented),
                    // but FCEUX next-frame dump still shows old values (partial clear).
                    val fOff2 = frame * 2048
                    val srcTask = fceuxRam[fOff2 + OPER_MODE_TASK].toInt() and 0xFF
                    val isLagFrame = diffs.size > 10 && srcTask == 0 &&
                        diffs.count { it.second == 0 && it.third != 0 } > diffs.size * 3 / 4
                    if (isLagFrame) {
                        lagFramesSkipped++
                    }

                    if (diffs.isNotEmpty() && !isLagFrame) {
                        for ((addr, kv, fv) in diffs) {
                            addrDivergenceCount[addr]++
                            if (addr !in firstDivFrame) firstDivFrame[addr] = frame
                        }
                        framesWithErrors++
                        totalDivergences += diffs.size

                        // Extra post-NMI dump for frame 9064
                        if (frame == 9064) {
                            fun hex2(b: Int) = (b and 0xFF).toString(16).padStart(2, '0')
                            println("  POST-NMI frame 9064 detailed:")
                            println("    xSpeed[2] (\$59): k=${hex2(kotlinFlat[0x59].toInt())} f=${hex2(fceuxRam[nextOff + 0x59].toInt())}")
                            println("    movDir[1] (\$47): k=${hex2(kotlinFlat[0x47].toInt())} f=${hex2(fceuxRam[nextOff + 0x47].toInt())}")
                            println("    pXPos (\$86): k=${hex2(kotlinFlat[0x86].toInt())} f=${hex2(fceuxRam[nextOff + 0x86].toInt())}")
                            println("    pPage (\$6D): k=${hex2(kotlinFlat[0x6D].toInt())} f=${hex2(fceuxRam[nextOff + 0x6D].toInt())}")
                            println("    eState[1] (\$1F): k=${hex2(kotlinFlat[0x1F].toInt())} f=${hex2(fceuxRam[nextOff + 0x1F].toInt())}")
                            println("    eYSpd[2] (\$A1): k=${hex2(kotlinFlat[0xA1].toInt())} f=${hex2(fceuxRam[nextOff + 0xA1].toInt())}")
                            println("    eYPos[2] (\$D0): k=${hex2(kotlinFlat[0xD0].toInt())} f=${hex2(fceuxRam[nextOff + 0xD0].toInt())}")
                            println("    eXPos[2] (\$88): k=${hex2(kotlinFlat[0x88].toInt())} f=${hex2(fceuxRam[nextOff + 0x88].toInt())}")
                            println("    eYMF[2] (\$435): k=${hex2(kotlinFlat[0x435].toInt())} f=${hex2(fceuxRam[nextOff + 0x435].toInt())}")
                            // All diffs:
                            println("    ALL ${diffs.size} diffs:")
                            for ((a, k, f) in diffs) {
                                println("      \$${a.toString(16).padStart(4, '0')}: k=${k.toString(16).padStart(2, '0')} f=${f.toString(16).padStart(2, '0')}")
                            }
                        }

                        // Detailed logging for watched addresses
                        val watchedDiffs = diffs.filter { it.first in WATCHED_ADDRS }
                        if (watchedDiffs.isNotEmpty() && watchedDivsLogged < 40) {
                            watchedDivsLogged++
                            val mode = fceuxRam[fOff2 + OPER_MODE].toInt() and 0xFF
                            val task = fceuxRam[fOff2 + OPER_MODE_TASK].toInt() and 0xFF
                            val eng = fceuxRam[fOff2 + GAME_ENGINE_SUBROUTINE].toInt() and 0xFF
                            val px = fceuxRam[fOff2 + PLAYER_X_POSITION].toInt() and 0xFF
                            println("Frame $frame WATCH (${diffs.size} diffs) M=$mode T=$task E=$eng PX=$px")
                            for ((addr, kv, fv) in watchedDiffs) {
                                println("  \$${addr.toString(16).padStart(4, '0')}: kotlin=${kv.toString(16).padStart(2, '0')} fceux=${fv.toString(16).padStart(2, '0')}")
                            }
                            // Show a few more non-watched diffs for context
                            val otherDiffs = diffs.filter { it.first !in WATCHED_ADDRS }.take(5)
                            for ((addr, kv, fv) in otherDiffs) {
                                println("  \$${addr.toString(16).padStart(4, '0')}: kotlin=${kv.toString(16).padStart(2, '0')} fceux=${fv.toString(16).padStart(2, '0')}")
                            }
                        }
                    }
                    comparedFrames++
                }
            }

            // Check progress (read from FCEUX state for consistency)
            if (fceuxRam != null) {
                val fOff = frame * 2048
                if (fOff + 2047 < fceuxRam.size) {
                    val world = (fceuxRam[fOff + WORLD_NUMBER].toInt() and 0xFF) + 1
                    val level = (fceuxRam[fOff + LEVEL_NUMBER].toInt() and 0xFF) + 1
                    val fMode = fceuxRam[fOff + OPER_MODE].toInt() and 0xFF

                    if (world > maxWorld || (world == maxWorld && level > maxLevel)) {
                        maxWorld = world
                        maxLevel = level
                        lastProgressFrame = frame
                        println("Frame $frame: Reached W$world-$level (FCEUX Mode=$fMode)")
                    }
                    if (world == 8 && level == 4) reachedW84 = true
                    if (reachedW84 && fMode == 2) {
                        gameCompleted = true
                        println("Frame $frame: GAME COMPLETED!")
                        break
                    }
                }
            }

            // Progress reporting
            if (frame % 2000 == 0) {
                println("Frame $frame/$totalFrames: W$maxWorld-$maxLevel" +
                    if (comparisonMode) " (diffs so far: $framesWithErrors/$comparedFrames frames)" else "")
            }
        }

        println("\n=== Results ===")
        println("Max level reached: W$maxWorld-$maxLevel")
        println("Reached W8-4: $reachedW84")
        println("Game completed: $gameCompleted")
        println("Errors (exceptions): $nmiErrorCount / $totalFrames frames")
        if (errorLocations.isNotEmpty()) {
            println("\nError locations (sorted by frequency):")
            for ((loc, count) in errorLocations.entries.sortedByDescending { it.value }) {
                println("  $count\t$loc")
            }
        }

        // Divergence report
        if (comparisonMode) {
            println("\n=== Divergence Report ===")
            println("Compared frames: $comparedFrames")
            println("Frames with errors: $framesWithErrors / $comparedFrames")
            println("Lag frames skipped: $lagFramesSkipped")
            println("Total divergent bytes: $totalDivergences")
            if (comparedFrames > 0) {
                println("Error rate: ${"%.2f".format(framesWithErrors * 100.0 / comparedFrames)}%")
            }

            val divergentAddrs = addrDivergenceCount.withIndex()
                .filter { it.value > 0 }
                .sortedByDescending { it.value }

            if (divergentAddrs.isNotEmpty()) {
                println("\nTop 30 divergent addresses (of ${divergentAddrs.size}):")
                for ((addr, count) in divergentAddrs.take(30)) {
                    val first = firstDivFrame[addr] ?: -1
                    println("  \$${addr.toString(16).padStart(4, '0')}: $count frames (${"%.1f".format(count * 100.0 / comparedFrames)}%) first@$first")
                }
            } else {
                println("\nNo divergences detected!")
            }
        }

        assertTrue(maxWorld > 1 || maxLevel > 1 || gameCompleted,
            "Should make progress past W1-1 (reached W$maxWorld-$maxLevel)")

        when {
            gameCompleted -> println("\nSUCCESS: Translation completed the TAS!")
            reachedW84 -> println("\nPARTIAL: Reached W8-4 but didn't detect completion")
            else -> println("\nINCOMPLETE: Only reached W$maxWorld-$maxLevel")
        }
    }
}
